### ISSUE TITLE
Stworzyć diagramy sekwencji na podstawie wybranych przypadków użycia.

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#10]
W uzgodnieniu z Programistą (@KamilGammert) należy stworzyć diagramy sekwencji dla minimum dwóch przypadków użycia. Proszę uwzględnić, iż diagram sekwencji służy do prezentowania interakcji pomiędzy istniejącymi obiektami oraz komunikatów (uwzględnionych w czasie), które przesyłane są między tymi obiektami.

**Comment by DamianGraczyk** [comment]
Przypominam o konieczności wykonania diagramów sekwencji dla minimum dwóch przypadków użycia.

**Comment by AndrzejPietrzak** [comment]
Diagramy zostały stworzone i umieszczone w repozytorium.

**Comment by DamianGraczyk** [comment]
W wyniku ustaleń z Klientem stwierdzono błędy w diagramach sekwencji, które muszą zostać poprawione. Należy zmodyfikować nazwy obiektów w diagramach sekwencji na takie, jakie występują w diagramie klas.

**Comment by AndrzejPietrzak** [comment]
Poprawiono diagramy sekwencji.

**Comment by DamianGraczyk** [comment]
Wykonano poprawnie.
