### ISSUE TITLE
Stworzyć avatary graczy dla aplikacji mobilnej "Milionerki".

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#11]
W uzgodnieniu z Programistą (@KamilGammert) stworzyć 6 avatarów będących graficzną personifikacją gracza w aplikacji "Milionerki".

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk w porozumieniu z Programistą @KamilGammert dodano do repozytorium awatary graczy, 3 męskie, 3 kobiece o wymiarach 300x300 pikseli.

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadomości.
