### ISSUE TITLE
Słownik danych dla bazy danych aplikacji mobilnej "Milionerki"

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#12]
Proszę wykonać słownik danych dla bazy danych aplikacji mobilnej "Milionerki".

**Comment by DamianGraczyk** [comment]
Przypominam o konieczności wykonania słownika danych dla bazy danych aplikacji mobilnej "Milionerki".

**Comment by leszeksierocki** [comment]
Utworzone

**Comment by DamianGraczyk** [comment]
Rozumiem, słownik bazy danych zostanie zaprezentowany w najbliższym czasie Klientowi.

**Comment by DamianGraczyk** [comment]
W wyniku ustaleń z Klientem stwierdzono, że dokument "Słownik bazy danych" odbiega od normy dokumentów typu Data Dictionary. Proszę dostosować dokument do obowiązującej normy. Zadanie te proszę wykonać we współpracy z członkiem grupy projektowej @kbarbasiewicz .

**Comment by DamianGraczyk** [comment]
Przypominam o konieczności poprawienia dokumentu.

**Comment by leszeksierocki** [comment]
Poprawione

**Comment by DamianGraczyk** [comment]
Wykonano poprawnie.
