### ISSUE TITLE
Implementacja bazy danych na podstawie modelu konceptualnego bazy danych aplikacji mobilnej "Milionerki".

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#13]
Proszę kontynuować proces deweloperski poprzez implemetację bazy danych na podstawie zaakceptowanego przez Klienta modelu konceptualnego bazy danych aplikacji mobilnej "Milionerki". Zadanie te, proszę wykonać we współpracy z @leszeksierocki .

**Comment by ghost** [comment]
Baza została zaimplementowana.

**Comment by DamianGraczyk** [comment]
Wykonano poprawnie.
