### ISSUE TITLE
Implementacja klasy RankingView zgodnie z diagramem klas aplikacji mobilnej "Milionerki".

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#14]
Realizacja procesu deweloperskiego - proszę o implementację klasy RankingView zgodnie z diagramem klas oraz zaakceptowaną makietą widoku tej klasy. Przy implementacji tej klasy proszę skorzystać z pomocy Grafika @kbarbasiewicz , który na bieżąco będzie dostarczał wymagane elementy interfejsu graficznego.

**Comment by ghost** [comment]
Widok został stworzony.

**Comment by DamianGraczyk** [comment]
W wyniku ustaleń Kierownika grupy projektowej z Klientem stwierdzono, że makieta widoku RankingView oraz widok zaimplementowanej klasy RankingView są graficznie bardzo słabe. Po dostarczeniu przez Grafika poprawionej wersji makiety tego widoku, proszę poprawić również widok implementowanej klasy zgodnie z dostarczoną makietą.

**Comment by ghost** [comment]
Wygląd został poprawiony.

**Comment by DamianGraczyk** [comment]
Numer pozycji w rankingu nachodzi na awatar. Proszę poprawić ten defekt.
Warto pomyśleć nad użyciem cyfr rzymskich, ale jest to pomysł, który zostanie przedyskutowany z Klientem.

Efekt poprawy proszę także uwzględnić w zrzucie ekranu aplikacji.

**Comment by ghost** [comment]
Poprawione, wygląd zgodnie z makietą.

**Comment by DamianGraczyk** [comment]
Implementacja klasy RankingView przebiegła prawidłowo, grafik w najbliższym czasie dostarczy elementy graficzne, które następnie należy podmienić w widoku klasy RankingView. Po wykonaniu tej czynności proszę zaktualizować screen widoku w folderze Aplikacja.
