### ISSUE TITLE
Zastosowanie diagramów czynności do analizy przypadków użycia.

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#15]
Proszę zastosować diagramy czynności do analizy wybranych dwóch przypadków użycia.

**Comment by DamianGraczyk** [comment]
Przypominam o konieczności wykonania diagramów czynności do analizy wybranych dwóch przypadków użycia.

**Comment by AndrzejPietrzak** [comment]
Dodano diagramy czynności.

**Comment by DamianGraczyk** [comment]
W wyniku ustaleń z Klientem zauważono błędy w jednym z diagramów czynności, które muszą zostać wyeleminowane. Proszę poprawić diagram czynności "Wyświetlenie wyników graczy", w którym nie został uwzględniony aktor GRACZ, który odpowiada za uruchomienie akcji.

**Comment by AndrzejPietrzak** [comment]
Poprawiono.

**Comment by DamianGraczyk** [comment]
Diagramy czynności wykonano poprawnie.
