### ISSUE TITLE
Makiety widoków - ujednolicenie koloru tła

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#16]
Proszę ujednolicić kolor tła występującego w makietach do jednego z ciemniejszych odcieni niebieskiego. Efekty pracy proszę na bieżąco konsultować z Programistą oraz Kierownikiem grupy.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Ujednolicono kolor tła i dodano poprawione makiety do repozytorium.

**Comment by DamianGraczyk** [comment]
Wykonano poprawnie.
