### ISSUE TITLE
Makieta widoku tworzenia profilu gracza.

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#17]
Do utworzonej makiety widoku wyboru awatara, proszę utworzyć makietę tworzenia profilu gracza (podanie imienia, nazwiska i nicku/pseudonimu gracza). Wygląd makiety proszę konsultować z Kierownikiem grupy oraz z Programistą.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Dodano do repozytorium makietę tworzenia profilu gracza.

**Comment by DamianGraczyk** [comment]
Wykonano poprawnie.
