### ISSUE TITLE
Makieta widoku wyboru profilu gracza

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#18]
Proszę, w uzgodnieniu z Kierownikiem grupy oraz Programistą, stworzyć makietę widoku wyboru profilu gracza. Makieta powinna zawierać listę dostępnych (utworzonych wcześniej) profili graczy oraz możliwość rezygnacji z wyboru profilu ("Powrót"), a także możliwość stworzenia nowego profilu gracza ("Nowy profil").

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Dodano do repozytorium makietę wyboru profilu.

**Comment by DamianGraczyk** [comment]
Makietę wykonano poprawnie.
