### ISSUE TITLE
Makieta widoku RankingView (wyświetlająca wyniki rozgrywek graczy).

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#19]
W wyniku ustaleń Kierownika grupy projektowej z Klientem stwierdzono, że makieta widoku RankingView (Makieta_Widoku_Najlepsze_Wyniki.png) jest graficznie bardzo słaba. Proszę wyróżnić różnymi kolorami (np. złoty, srebny, brązowy, biały) miejsca w rankingu. Miejsca 1-3 można dodatkowo wyróżnić odznaczeniami. 

Proszę poprawić makietę tego widoku i przekazać ją do akceptacji przez Kierownika grupy projektowej.
Proszę zmienić nazwę makiety widoku na "RankingView".

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Poprawioną makietę umieszczono w repozytorium, nosi teraz nazwę RankingView.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Poprawioną makietę umieszczono w repozytorium, nosi teraz nazwę RankingView.

**Comment by DamianGraczyk** [comment]
Rozumiem. Warto zastanowić się nad użyciem cyfr rzymskich przy wyświetlaniu numeru pozycji w rankingu. Zostanie to omówione z Klientem.

**Comment by DamianGraczyk** [comment]
W wyniku ustaleń Kierownika grupy projektowej z Klientem stwierdzono, iż makieta widoku RankingView wykonana została poprawnie. Należy jednak poprawić kolory, na które należy nałożyć teksturę, aby efekt wizualny był lepszy od obecnego.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk delikatnie poprawiono kolory oraz nałożono teksturę w celu wyróżnienia pierwszych trzech pozycji graczy. Plik RankingView.png podmieniono w repozytorium.
