### ISSUE TITLE
Specyfikacja wymagan

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#2]
Poprawić specyfikację wymagań:
1) Punkt "Zakres" z rozdziału "Wstęp" jest pomieszany z wyborem technologii - generalnie powininna być funkcjonalność. Usunąć informacje dotyczące środowiska projektowego. 
2) "Głównym założeniem projektu jest uzyskanie grywalnej wersji aplikacji, której trudność rośnie wraz z kolejnymi progami gwarantowanymi." powinno być pierwszym zdaniem punktu "Zakres" rozdziału "Wstęp" Specyfikacji wymagań.
2) Usunąć z punktu "Definicje, akronimy i skróty" rozdziału Wstęp błędne hasła. Pozostawić poprawną definicję "Baza pytań" oraz dodać kolejne akronimy takich pojęć jak "Próg gwarantowany" czy "Prowadzący".

**Comment by AndrzejPietrzak** [comment]
Specyfikacja wymagań została poprawiona.
