### ISSUE TITLE
Komentarze dokumentacyjne.

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#20]
W wyniku ustaleń na linii Klient - Kierownik grupy projektowej ustalono, że implementowany kod powienien zawierać komentarze dokumentacyjne. Proszę dodać komentarze do już istniejących klas i metod, a także uwzględnić zalecenie Klienta i Kierownika grupy projektowej przy dalszej implementacji.

**Comment by DamianGraczyk** [comment]
Zmiana przydziału osoby do tego zadania. Zadanie pozostaje bez zmian.

**Comment by leszeksierocki** [comment]
Wykonano

**Comment by DamianGraczyk** [comment]
Zadanie wykonano poprawnie.
