### ISSUE TITLE
Kontynuacja prac deweloperskich - realizacja funkcjonalności tworzenia profilu gracza z wyborem awatara.

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#21]
Proszę kontynuować proces deweloperski poprzez implementację funkcjonalności tworzenia profilu gracza z wyborem awatara zgodnie z dostarczonymi i zaakceptowanymi makietami widoków przez Grafika @kbarbasiewicz .

**Comment by ghost** [comment]
Zaimplementowane.

**Comment by DamianGraczyk** [comment]
W wyniku ustaleń Kierownika grupy projektowej z Klientem stwierdzono, iż w zaimplementowanej funkcjonalności tworzenia profilu należy zmodyfikować niektóre napisy [Label] znajdujące się w widoku. Zmiany powinny objąć takie sformułowania jak "Wybór avataru", czy "Załóż", które należy zmienić na poprawne językowo. 

Dodatkowo, kolor linii określającej obszar wpisywania [Text Field] powinien być zdecydowanie lepiej widocznym. Dobrym rozwiązaniem jest zastosowanie takiego samego koloru jak treści.
