### ISSUE TITLE
Scenariusze testów funkcjonalnych

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#22]
Proszę stworzyć scenariusze testów funkcjonalnych we współpracy z @kbarbasiewicz .
W każdym ze scenariuszy powinny znaleźć się takie elementy jak m.in.:
- czego dotyczy scenariusz,
- cel testu,
- sposób dostępu,
- scenariusz (w postaci kroków testowych) zawierający akcje użytkownika i odpowiedzi systemu
- ocenę testu.

**Comment by DamianGraczyk** [comment]
@leszeksierocki przypominam o konieczności wykonania scenariuszy testów funkcjonalnych.

**Comment by leszeksierocki** [comment]
Zakończone

**Comment by DamianGraczyk** [comment]
W wyniku konsultacji na linii Klient - Kierownik grupy projektowej wykryto błędy w scenariuszach testów funkcjonalnych, które muszą zostać wyeleminowane. Głównie dotyczy to słownictwa, nazewnictwa i nadmiarowości (np. "przez gracza").

Przypominam, że aktorem aplikacji jest gracz.

Numer scenariusza powinien odpowiadać temu z diagramu przypadków użycia.

Scenariusz, który "dotyczy SPU 1.0" nie jest skończony.

Scenariusz, który "dotyczy SPU 1.2" posiada błędy, które dotyczą słownictwa (np. "wciśnięta opcja"),  a także nadmiarowości ("przez gracza"). Ponadto, należy zmodyfikować odpowiedź systemu w punkcie 10, np. na komunikat utworzenia konta.

**Comment by leszeksierocki** [comment]
Błędy zostały poprawione

**Comment by DamianGraczyk** [comment]
Zauważono kolejne:

P3: Sposób dostępu     Widok wywoływany jest z poziomu menu głównego aplikacji po wybraniu opcji „Rozpocznij grę”. W wyniku wybrania tej opcji ukaże się możliwość wybrania jednej z dwóch możliwości (jedna z nich to tworzenie nowego profilu gracza).

P3: Uwagi        Należy wyeliminować próby utworzenia profilu bez podawania danych oraz wprowadzić zabezpieczenia dotyczące długości wpisanego tekstu.

P3: Odpowiedź systemu    10. Utworzenie profilu gracza - potwierdzenie.

P4: Sposób dostępu: ...Po wybraniu tej opcji uzyskujemy możliwość wybrania jednego z utworzonych wcześniej profili graczy.

Ocena zawsze Pozytywna lub Negatywna - trzymaj się konwencji, którą przyjmujesz (piszesz raz pozytywna/negatywna, raz pozytywny/negatywny)

Nazwy etykiet i przycisków, na które powołujesz się w scenariuszach testowych, powinny odpowiadać rzeczywistym nazwom dostępnym w aplikacji.

**Comment by leszeksierocki** [comment]
Poprawiono

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadmości.
