### ISSUE TITLE
Dokument detaliczny projektu

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#24]
Należy wykonać główny dokument etapu projektowania, który ma nazwę "Dokument Detaliczny Projektu", w skrócie DDP. 

Zadanie te należy wykonać we współpracy z @kbarbasiewicz .

Dokument Detaliczny Projektu to szczegółowy opis rozwiązania problemu określonego w dokumencie wymagań oprogramowania. DDP to także dokument, w którym gromadzone są na bieżąco informacje odnośnie budowy i działania oprogramowania. 

Przykładowa zawartość DDP: 

Informacja organizacyjna 
- Streszczenie 
- Spis treści 
- Formularz statusu dokumentu 
- Zapis zmian w stosunku do ostatniej wersji 

OPIS OGÓLNY 
1. WPROWADZENIE 
   - 1.1. Cel DDP 
   - 1.2. Zakres DDP 
   - 1.3. Definicje, akronimy, skróty 
   - 1.4. Odsyłacze 
   - 1.5. Krótkie omówienie treści dokumentu 
2. STANDARDY PROJEKTU, KONWENCJE, PROCEDURY 
   - 2.1. Standardy projektowe 
   - 2.2. Standardy dokumentacyjne 
   - 2.3. Konwencje nazwowe 
   - 2.4. Standardy programistyczne 
   - 2.5. Narzędzia rozwijania oprogramowania 
3. SPECYFIKACJA KOMPONENTÓW  (gdzie 3. to n.)
   - n [IDENTYFIKATOR KOMPONENTU] 
   - n.1. Typ 
   - n.2. Cel 
   - n.3. Funkcja 
   - n.4. Komponenty podporządkowane 
   - n.5. Zależności 
   - n.6. Interfejsy 
   - n.7. Zasoby 
   - n.8. Odsyłacze 
   - n.9. Przetwarzanie 
   - n.10. Dane 

W przypadku dołączenia kodu źródłowego, tj. listingu, należy umieścić go jako dodatek do DDP. Jest to tylko przykładowa struktura tego rodzaju dokumentu.

Dokument ten należy stale aktualizować.

**Comment by AndrzejPietrzak** [comment]
Dodano.

**Comment by DamianGraczyk** [comment]
Proszę pamiętać o cotygodniowej aktualizacji Dokumentu Detalicznego Projektu.

**Comment by AndrzejPietrzak** [comment]
Uaktualniono

**Comment by DamianGraczyk** [comment]
Proszę kontynuować uzupełnianie Dokumentu Detalicznego Projektu.

**Comment by AndrzejPietrzak** [comment]
Dodano specyfikację kolejnych komponentów.

**Comment by DamianGraczyk** [comment]
Proszę o zakończenie prac nad Dokumentem Detalicznym Projektu.

**Comment by AndrzejPietrzak** [comment]
Prace nad dokumentem zostały zakończone.

**Comment by DamianGraczyk** [comment]
Zatwierdzam do akceptacji przez Klienta. Zamykam.
