### ISSUE TITLE
Utworzenie aktywności GameActivity wraz z menu bocznym wysuwanym

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#25]
Realizacja procesu deweloperskiego - proszę o utworzenie aktywności GameActivity wraz z menu bocznym wysuwanym.

**Comment by DamianGraczyk** [comment]
Proszę kontynuować implementację aktywności GameActivity. Proszę o implementację mechanizmów: 
- losowania pytania, 
- wyświetlania pytania,
- wyświetlania odpowiedzi,
- sprawdzenia poprawności wybranej odpowiedzi przez Gracza,
- rezygnacji z dalszej gry,
- zakończenia rozgrywki po udzieleniu błędnego pytania lub po zdobyciu głównej wygranej (po udzieleniu poprawnej odpowiedzi na wszystkie pytania),
- zapisywanie aktualnej wygranej Gracza.

**Comment by ghost** [comment]
Wykonano, screen dodany.
