### ISSUE TITLE
Baza pytań dla aplikacji Milionerki

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#26]
Zadanie proszę wykonać razem z @leszeksierocki .

Należy stworzyć plik tekstowy, który zawierać będzie numer pytania, pytanie, odpowiedzi oraz poziom trudności. Plik ten będzie następnie przekazany Programiście @KamilGammert , który na jego podstawie dokonana implementacji.

Należy zachować następującą strukturę:
VALUES(id, pytanie, dobra odp, zła odp, zła odp, zła odp, poziom trundności), 
(id, pytanie, dobra odp, zła odp, zła odp, zła odp, poziom trundności), 
(id, pytanie, dobra odp, zła odp, zła odp, zła odp, poziom trundności),

gdzie:
- id - unikalna wartość liczbowa
- pytanie, dobra odp, zła odp- string w  ' '
- poziom trudności - wartość liczbowa od 1 do 10

Utworzony przeze mnie plik wraz z 17 pytaniami dostępny znajduje się w głównym katalogu projektu w folderze o nazwie "VIII Baza pytań". Plik ten nosi nazwę "bazaPytan.txt" .

Dla ułatwienia pracy stworzona została aplikacja wspomagająca proces dodawania pytań do pliku tekstowego zgodnie z przyjętą konwencją. Program należy uruchomić w jednym katalogu z plikiem tekstowym "bazaPytan.txt". Proszę o podawanie każdorazowo unikalnego numeru pytania.

Proszę o dodanie minimum 15 unikalnych pytań na osobę, tak, aby w efekcie końcowym, na każdy poziom trudności przypadało minimum jedno pytanie.

Wskazuję harmonogram pracy: w pierwszej kolejności swoją część pytań dodaje @kbarbasiewicz , następnie @leszeksierocki .

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk dodano 15 pytań do pięciu najwyższych poziomów trudności, proszę o przekazanie uprawnień @leszeksierocki.

**Comment by DamianGraczyk** [comment]
Dodałem ze swojej strony kolejne pytania. Proszę o dopisanie minimum 15 unikalnych pytań (każde o unikalnym numerze) do pliku z uwzględnieniem tych poziomów pytań, do których przydzielono najmniejszą liczbę pytań.

**Comment by leszeksierocki** [comment]
Pytania zostały dodane

**Comment by ghost** [comment]
W wyniku nieoczekiwanego błędu należy zmienić schemat na:
question_values[x] = new String[]{"Pytanie", "Poprawna odp", "Zła odp", "Zła odp", "Zła odp", "poziom trudności"};

gdzie:
- x to kolejna wartość liczbowa począwszy od 0
- poziom trudności to liczba 
- wszystkie elemnty należy napisać w cudzysłowiu "aaa"

**Comment by DamianGraczyk** [comment]
@leszeksierocki, proszę o dodanie kolejnych 30 unikatowych pytań do pliku z bazą pytań.

**Comment by leszeksierocki** [comment]
wykonano

**Comment by DamianGraczyk** [comment]
Baza pytań została wielokrotnie aktualizowana przez moją osobę. Na ten moment ilość pytań w bazie jest  wystarczająca.
