### ISSUE TITLE
Testy funkcjonalne

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#27]
Proszę wykonać testy funkcjonalne na podstawie przygotowanych scenariuszy testów funkcjonalnych. W przypadku oceny negatywnej testu, proszę wykonać raport, w którym wskazane zostaną wykryte błędy w działaniu. Raport ten należy dostarczyć do programisty @KamilGammert  oraz kierownika grupy projektowej.

**Comment by leszeksierocki** [comment]
Testy zostały przeprowadzone i przekazano znalezione błedy

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadomości.
