### ISSUE TITLE
Ikona aplikacji "Milionerki"

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#28]
Proszę wykonać ikonę aplikacji "Milionerki" o następujących parametrach:

Tło: Transparentne
Rozdzielczość: 96x96px
Format: PNG

Termin wykonania zadania do: 04.05.2015r.

**Comment by kbarbasiewicz** [comment]
Dodano ikonę w postaci litery M, transparentna o wielkości 96x96 pikseli.

**Comment by DamianGraczyk** [comment]
Proszę poprawić ikonę w postaci litery M tak, aby miała ona wszystkie krawędzie ramki litery. Warto dodać także teksturę na ikonę. Proszę zachować kolorystykę zgodną z tworzoną aplikacją.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Poprawioną ikonę umieszczono w repozytorium.

**Comment by DamianGraczyk** [comment]
Ikona czeka na akceptację Klienta.

**Comment by DamianGraczyk** [comment]
Klient nie zgłosił uwag.
