### ISSUE TITLE
Kolejne testy funkcjonalne aplikacji Milionerki

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#29]
Proszę przygotować scenariusze testów funkcjonalnych obejmujące między innymi:
- użycie kół ratunkowych w grze "Milionerki",
- udzielenie błędnej odpowiedzi na pytanie (zerowanie wyniku gracza, koniec rozgrywki),
- udzielenie poprawnej odpowiedzi na pytanie (przypisanie aktualnej wygranej, kontynuacja rozgrywki),
- rezygnacja z dalszej rozgrywki (zapis wyniku z aktualną wygraną w momencie zakończenia rozgrywki).

Wyżej wymienione testy funkcjonalne, po akceptacji przez kierownika grupy projektowej, należy wykonać i przygotować raport dla programisty w przypadku, gdyby test wypadł negatywnie.

**Comment by leszeksierocki** [comment]
Utworzono odpowiednie scenariusze do wyżej wymienionych funkcji. Dokumenty te czekają na akceptację.

**Comment by DamianGraczyk** [comment]
Wykryto bardzo dużo błędów w utworzonych scenariuszach testów funkcjonalnych. Po ich poprawieniu proszę przejść do fazy testowania aplikacji na podstawie przygotowanych scenariuszy testów funkcjonalnych. Standardowo, w przypadku wykrycia błędów, proszę stworzyć raport, który następnie należy przekazać programiście @KamilGammert .

P6 (Ustalić poprawną kolejność akcji użytkownika / odpowiedzi systemu): 
Cel testu: Testowanie poprawności działania kół ratunkowych.

Sposób dostępu: Wybranie jednej z trzech graficznych reprezentacji kół ratunkowych znajdujących się w górnej części widoku rozgrywki.

Akcja użytkownika:
9. Zamknięcie okna dialogowego wybranego koła ratunkowego.

Odpowiedź systemu: 
8. Wyświetlenie okna dialogowego zgodnego z wybranym kołem ratunkowym, np. wyświetlenie odpowiedzi zaproponowanej przez "przyjaciela" dla koła ratunkowego "telefon do przyjaciela.

P7 (Ustalić poprawną kolejność akcji użytkownika / odpowiedzi systemu): 
Cel testu: Testowanie działania aplikacji po udzieleniu błędnej odpowiedzi na zadane pytanie.

Akcja użytkownika: 
7. Udzielenie błędnej odpowiedzi na wylosowane pytanie. 
9. Akceptacja okna dialogowego informującego o udzieleniu błędnej odpowiedzi.

Odpowiedź systemu: 
8. Wyświetlenie informacji o udzieleniu błędnej odpowiedzi na zadane pytanie. 
10. Brak zapisu wyniku gracza do tabeli najlepszych wyników. Wyświetlenie tabeli najlepszych wyników graczy.

P8 (Ustalić poprawną kolejność akcji użytkownika / odpowiedzi systemu):
Cel testu: Testowanie działania aplikacji po udzieleniu poprawnych odpowiedzi na wszystkie zadane pytania.

Akcja użytkownika: 
7. Udzielenie poprawnych odpowiedzi na każde kolejne wylosowane pytanie. 
9. Zamknięcie okna dialogowego z informacją o głównej nagrodzie.

Odpowiedź systemu: 
6. Wyświetlenie pierwszego pytania w grze oraz kolejnych po udzieleniu przez użytkownika poprawnych odpowiedzi.
8. Wyświetlenie okna dialogowe, po udzieleniu poprawnych odpowiedzi na wszystkie zadane pytania, informującego użytkownika o zdobyciu głównej nagrody.
10. Zapis wyniku gracza i wyświetlenie odświeżonej tabeli wyników wszystkich graczy.

P9: Sposób dostępu: Widok wywoływany przez użytkownika w czasie trwania rozgrywki za pomocą wysuwanego menu bocznego i wybraniu opcji "Zrezygnuj".

**Comment by leszeksierocki** [comment]
Poprawione

**Comment by leszeksierocki** [comment]
Podczas testów nie stwierdzono problemu z działaniem funkcji. Jednak osobiście mam kilka uwag dotyczących samego wyglądu aplikacji. Według mnie przedstawienie tekstów prowadzącego w ten sposób jak teraz nie jest poprawne. Bardzo mnie denerwowało to, że musiałem klikać więcej tylko po to aby wyłączyć okienko z tekstem. Również nieestetyczne jest zaznaczenie odpowiedzi, którą wybraliśmy. Widać wyraźnie, że zaznaczenie po lewej stronie jest znacznie mniejsze niż to po prawej i powinno zostać to poprawione.

**Comment by leszeksierocki** [comment]
Podczas wykonywania ponownych testów okazało się że najlepsze wyniki nie są poprawnie sortowane. O błędzie został poinformowany @KamilGammert

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadomości.
