### ISSUE TITLE
 Model konceptualny bazy danych aplikacji mobilnej "Milionerki"

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#3]
1. Stworzyć model konceptualny bazy danych aplikacji mobilnej "Milionerki" zawierającej takie encje jak:
   a) GRACZE,
   b) PYTANIA_ODPOWIEDZI,
   c) TEKSTY_PROWADZACEGO,
   d) WYNIKI.
2. Wraz z programistą (@KamilGammert) i kierownikiem grupy projektowej (@DamianGraczyk) należy dokonać analizy modelu konceptualnego bazy danych dla aplikacji mobilnej "Milionerki". Zmodyfikować model konceptualny bazy danych w przypadku zaistnienia takiej konieczności w wyniku uzgodnień z programistą i kierownikiem grupy projektowej.
3. Ostateczną wersję modelu konceptualnego przesłać do repozytorium grupy projektowej.

**Comment by leszeksierocki** [comment]
W dniu dzisiejszym został dodany model konceptualny bazy danych.

**Comment by DamianGraczyk** [comment]
Encje powinny wyglądać następująco: 

Gracze (Pseudonim VA25 KP, Imie_Gracza VA25, Nazwisko_Gracza VA25);

Pytania_Odpowiedzi(ID_Pytania Integer KP, Pytanie VA100, Poprawna_Odp VA40, Bledna_Odpowiedz1 VA40, Bledna_Odpowiedz2 VA40, Bledna_Odpowiedz3 VA40);

Teksty_Prowadzacego(ID_Tekstu Integer KP, Tekst_Prowadzacego VA100);

Wyniki(ID_Wynik Integer KP (autoincrement), UzyskanyWynik Integer, Czas_Gry float, Data_Wpisu Date);

Pierwotne założenie zakładało, że teksty prowadzącego będą losowane z puli dostępnych tekstów. Zatem poprawnie byłoby utworzyć encję:
    a) Pytania_Odpowiedzi jako niezależną encję, która nie ma żadnych relacji z pozostałymi encjami modelu.
    b) Teksty_Prowadzacego jako niezależną encję, która nie ma żadnych relacji z pozostałymi encjami modelu. 

W przypadku zmiany przyjętego założenia i przypisania tekstów prowadzącego do konkretnego pytania, relacja Pytania_Odpowiedzi --> Teksty_Prowadzacego powinna być typu jeden do wielu (kilka możliwych tekstów prowadzącego przypisane do jednego pytania).

Między encją Gracze a Pytania_Odpowiedzi nie ma żadnej relacji - są to dwie niezależne encje.
Proponuję także zmienić relację Gracze ---> Wyniki na 1 do 0,n. Dany gracz może utworzyć konto, ale nie musi rozegrać żadnej rozgrywki, a tym samym nie posiadać żadnego wyniku.

Model po wprowadzeniu poprawek proszę skonsultować z programistą (@KamilGammert).
Dodatkowo, atrybut Prawdopodobienstwo_Wypadniecia w encji Teksty_Prowadzacego proszę także skonsultować z programistą (@KamilGammert). Atrybut ten może okazać się w zupełności niepotrzebny, przez co nie ująłem go w poprawkach.

**Comment by ghost** [comment]
Proszę dodać:
- atrybut Poziom_Trudności INT2 do encji Pytania_Odpowiedzi w celu określenia poziomu trudności
- atrybut Prawdopodobienstwo_Wypadniecia INT3 w encji Teksty_Prowadzacego

**Comment by leszeksierocki** [comment]
Model został poprawiony zgodnie z uwagami kierownika projektu oraz programisty

**Comment by DamianGraczyk** [comment]
W wyniku uzgodnień Kierownika grupy projektowej z Klientem wykryto błąd w modelu konceptualnym bazy danych.

Proszę poprawić model konceptualny bazy danych aplikacji mobilnej "Milionerki". W oparciu o uwagi Klienta i Kierownika grupy, należy zmodyfikować model konceptualny bazy danych poprzez poprawienie nazwy relacji (nazwa relacji nie może być nazwana "Relationship") oraz dodanie encji TekstyKoloTelefon. Proszę także o poprawienie istniejących literówek w nazwach atrybutów.

**Comment by DamianGraczyk** [comment]
Przypominam o konieczności poprawienia modelu konceptualnego bazy danych zgodnie z przekazanymi instrukcjami.

**Comment by leszeksierocki** [comment]
Poprawione

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadomości, poprawiony model zostanie zaprezentowany Klientowi.
