### ISSUE TITLE
Kontynuacja implementacji aktywności GameActivity

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#30]
Proszę o implementację mechanizmów:
- wszystkich trzech kół ratunkowych ("pytanie do publiczności", "telefon do przyjaciela" i "pół na pół"),
- wyświetlania losowych tekstów prowadzącego w czasie rozgrywki, np. po zaznaczeniu odpowiedzi,
- wyświetlania losowych tekstów "przyjaciela" przy wykorzystaniu koła ratunkowego "telefon do przyjaciela".

**Comment by ghost** [comment]
Zakończone implementację ww. funkcjanolności.

**Comment by DamianGraczyk** [comment]
Proszę oczekiwać na raport testowy od @leszeksierocki celem dokonania ewentualnych poprawek w aplikacji.
