### ISSUE TITLE
Baza tekstów prowadzącego dla aplikacji Milionerki

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#31]
Należy wykonać plik tekstowy z bazą tekstów prowadzącego dla aplikacji Milionerki. Należy zachować poniższą strukturę:

text_leading_value[0] = new String[]{"Czy jesteś pewien tej odpowiedzi?", "3"};
text_leading_value[1] = new String[]{"Jesteś pewien?", "1"};
...
text_leading_value[n] = new String[]{"Czy jesteś pewien tej odpowiedzi?", "x"};,

gdzie n - to unikalny numer(proszę zachować kolejność w pliku i kontynuować numerację po ostatnim numerze),
x - prawdopodobieństwo wypadnięcia od 1 do 3

Aplikacja wspomagająca dodawanie tekstów prowadzącego pojawi się w późniejszym czasie.
Wymagana liczba tekstów prowadzącego przez @kbarbasiewicz wynosi: 15.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk dodano 15 tekstów.
