### ISSUE TITLE
Baza tekstów przyjaciela dla aplikacji Milionerki

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#32]
Należy wykonać plik tekstowy z bazą tekstów przyjaciela dla aplikacji Milionerki. Należy zachować poniższą strukturę:

text_friends_value[0] = new String[]{"Chyba znam odpowiedź", "3"};
text_friends_value[1] = new String[]{"Możliwe, że jest to:", "2"};
text_friends_value[2] = new String[]{"Chyba:", "1"};
...
text_friends_value[n] = new String[]{"Chyba znam odpowiedź", "n"};

gdzie n - to unikalny numer (proszę zachować kolejność w pliku i kontynuować numerację po ostatnim numerze),
x - prawdopodobieństwo wypadnięcia od 1 do 3

Aplikacja wspomagająca dodawanie tekstów prowadzącego pojawi się w późniejszym czasie.
Wymagana liczba tekstów prowadzącego przez @kbarbasiewicz wynosi: 15.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Dodano 15 tekstów.
