### ISSUE TITLE
Konieczne poprawki w wyglądzie i funkcjonalności aplikacji

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#33]
W wyniku ustaleń na linii Klient - Kierownik grupy projektowej ustalono, iż należy:
- zwiększyć czcionkę w aktywności "O grze",
- przy wyświetleniu tekstu prowadzącego w momencie udzielania odpowiedzi na zadane pytanie w rozgrywce należy dodać przyciski akcji, np. "Potwierdzam odpowiedź", "Wybieram inną odpowiedź" (zasada Tak/Nie),
- wydłużyć czas wyświetlania informacji w Intencie o udzieleniu błędnej/poprawnej odpowiedzi,
- poinformować gracza o zdobyciu głównej wygranej, a także o zapisaniu jego wyniku na liście "Najlepszych wyników". Po akceptacji przez gracza komunikatu należy zapytać go, czy chce wyświetlić listę "Najlepszych wyników", bądź poinformować go o wyświetleniu listy "Najlepszych wyników".

**Comment by ghost** [comment]
Wszystkie uwagi zostały zaimplementowane.

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadomości.
