### ISSUE TITLE
Diagram przypadków użycia aplikacji mobilnej "Milionerki"

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#4]
1. Wykonać diagram przypadków użycia, tj. graficznie zaprezentowanej własności systemu tak, jak są one widziane po stronie użytkownika, dla aplikacji mobilnej "Milionerki".
2. Skonsultować utworzony diagram przypadków użycia z kierownikiem grupy projektowej (@DamianGraczyk) i dokonać ewentualnych poprawek.
3. Przesłać wersję finalną diagramu przypadków użycia do repozytorium grupy projektowej.

**Comment by AndrzejPietrzak** [comment]
Przesłano diagram przypadków użycia.

**Comment by DamianGraczyk** [comment]
Proszę dodać komentarze do diagramu przypadków użycia aplikacji mobilnej "Milionerki". Nazwy dla przypadków użycia powinny być krótkie i jednoznacznie określać charakter zadania/funkcji.

**Comment by AndrzejPietrzak** [comment]
Poprawiono.

**Comment by DamianGraczyk** [comment]
W wyniku uzgodnień Kierownika grupy projektowej z Klientem wykryto błędy w modelu przypadków użycia.

Proszę poprawić diagram przypadków użycia. W oparciu o uwagi Klienta i Kierownika grupy, należy zastosować się do wymienionych poniżej uwag:
- poprawić błędne kierunki extend,
- diagram przypadków użycia nie uwzględnia czasu,
- "Udzielono poprawnej odpowiedzi" oraz "Udzielono błędnej odpowiedzi" to nie przypadki użycia;
- Przypadki użycia "Najlepsze wyniki" oraz "O grze" powinny być poprzedzone (wywodzić się) z przypadku użycia pn. "Informacja".

**Comment by AndrzejPietrzak** [comment]
Przesłano poprawioną wersję w oparciu o wskazówki Kierownika.

**Comment by DamianGraczyk** [comment]
Przyjąłem. Poprawiona wersja diagramu przypadków użycia zostanie omówiona z Klientem.

**Comment by DamianGraczyk** [comment]
Proszę dodać numerację do przypadków użycia.

**Comment by AndrzejPietrzak** [comment]
Dodano.
