### ISSUE TITLE
Makieta widoku StartView oraz GameView

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#5]
1. W porozumieniu Grafik - Programista (@KamilGammert) poprawić makietę widoku StartView (Hyperlink zamiast Button) oraz GameView (zwiększyć nacisk na nastrój rozgrywki poprzez dodanie gracza i prowadzącego w widoku rozgrywki) aplikacji mobilnej "Milionerki".

**Comment by DamianGraczyk** [comment]
@kbarbasiewicz proszę o wstawienie poprawionych makiet widoków StartView oraz GameView.

**Comment by kbarbasiewicz** [comment]
Makiety widoków zostały poprawione i przesłane do repozytorium.

**Comment by DamianGraczyk** [comment]
@kbarbasiewicz Po ustaleniach z Klientem zostaną przekazane kolejne instrukcje dotyczące poprawek makiet widoku StartView oraz GameView.

**Comment by DamianGraczyk** [comment]
Makiety StartView oraz GameView zostały poprawione i zaakceptowane przez Klienta.
