### ISSUE TITLE
Inne makiety widoków

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#6]
1. W porozumieniu Grafik - Programista (@KamilGammert) stworzyć pozostałe (brakujące) widoki aplikacji mobilnej "Milionerki", takie jak dialogi, wybór awatara (personifikacja osoby w grze), użycie kół ratunkowych, czy wyniki.

**Comment by DamianGraczyk** [comment]
@kbarbasiewicz proszę o wstawienie brakujących makiet widoków.

**Comment by DamianGraczyk** [comment]
Dodano do repozytorium dwie makiety widoków kół ratunkowych: "Pytanie do publiczności" oraz "Telefon do przyjaciela".

**Comment by kbarbasiewicz** [comment]
Dodano makietę koła ratunkowego "50:50"

**Comment by DamianGraczyk** [comment]
Dodano do repozytorium makietę widoku "Najlepsze wyniki".

**Comment by DamianGraczyk** [comment]
@kbarbasiewicz przypominam o konieczności wykonania makiety widoku tworzenia/wyboru profilu gracza.

**Comment by kbarbasiewicz** [comment]
@DamianGraczyk Dodano do repozytorium makietę widoku wyboru awatara gracza.

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadomości.
