### ISSUE TITLE
Rozpoczęcie prac deweloperskich - realizacja pierwszej funkcjonalności oraz implementacja bazy danych.

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#7]
1. Rozpoczęcie prac deweloperskich - realizacja funkcjonalności "O grze - dostarcza informacji o systemie rozgrywki, wersji gry oraz dane autorów" oraz implementacja bazy danych po zaakceptowaniu modelu konceptualnego.

**Comment by ghost** [comment]
- Dodano 1 button i 2 hiperłącza do ekranu startowego.
- Zaimplementowano aktywność "O grze", proszę o zapoznanie się z [opisem](https://github.com/ProjektStudencki/Milionerki/blob/master/Aplikacja/res/values/strings.xml), ewentualne zredagowanie tekstu i przekazanie go do mnie w celu aktualizacji. 
- Dodano wstępną implementację SQLite, wymagane jest jeszcze utworzenie tabel zgodnie z modelem konceptualnym bazy.

**Comment by DamianGraczyk** [comment]
Proszę poprawić literówki występujące string name= "title_wersja" oraz "text_autorzy".

Zmodyfikować zawartość string name="text_system_rozgrywki" na następującą:

Gra Milionerki opiera się na większości zasad popularnego teleturnieju "Milionerzy".
Założenia gry są bardzo proste. Aby zdobyć tytułową nagrodę miliona należy odpowiedzieć na 15 zadanych pytań przez prowadzącego. Istnieją dwa progi gwarantowane - pierwszy z nich po 5. pytaniu (1 000) oraz drugi z nich po 10. pytaniu (32 000). Do wykorzystania są trzy koła ratunkowe: pytanie do publiczności, telefon do wirtualnego przyjaciela oraz pół na pół.

Prosiłbym o zmianę wersji na 0.01 lub 1.00, gdyż jest to pierwsza wersja znajdująca się w repozytorium.

Wygląd okna należy dopracować poprzez ustawienie odpowiedniej kolorystyki oddającej klimat teleturnieju, a także dodanie niezbędnych grafik takich jak logo. Po ustaleniach z Klientem zostaną przekazane kolejne poprawki, które następnie należy wdrożyć.

**Comment by ghost** [comment]
- Dodano logo
- Poprawiono literówki
- Zmieniono opis
- Zmieniono wersją na 0.01, wersję 1.00 zarezerwowałbym na wydanie finalne
- Wygląd oraz kolorystykę proszę dopracować z @kbarbasiewicz

**Comment by DamianGraczyk** [comment]
W wyniku uzgodnień Kierownika grupy projektowej z Klientem wykryto błędy realizacji pierwszych funkcjonalności.
- Proszę zmienić nazwę aktywności AboutMeView na AboutView lub inną, która będzie jednoznacznie identyfikowała klasę.
- Ścieżka "src/com/example" projektu aplikacji mobilnej "Milionerki" nie jest poprawnie nazwana ("example"). 
- W wyniku rozpoczętego procesu deweloperskiego proszę o implementację klas StartActivity oraz AboutView na podstawie dostarczonego diagramu klas zgodnie z zaakceptowanymi makietami widoków przez Klienta.

**Comment by ghost** [comment]
Poprawione wszystkie w/w uwagi oraz dodano folder "screeny", gdzie umieszczono aktualny wygląd ekranu startowego i "O grze".

**Comment by DamianGraczyk** [comment]
Proszę o wyeleminowanie literówek występujących w strings.xml (np. text_autorzy).

**Comment by ghost** [comment]
Poprawione

**Comment by DamianGraczyk** [comment]
Przyjąłem do wiadomości.

**Comment by DamianGraczyk** [comment]
W aktywności StartActivity należy wyróżnić opcje w menu, które docelowo są typu Hyperlink. Można to osiągnąć poprzez ustawienie koloru lub podkreślenia dla danej opcji z menu.

**Comment by ghost** [comment]
Poprawione

**Comment by DamianGraczyk** [comment]
Wykonano poprawnie.
