### ISSUE TITLE
Stworzyć diagram klas aplikacji mobilnej "Milionerki"

### ISSUE THREAD

**Issue by DamianGraczyk** [ProjektStudencki/Milionerki#9]
W uzgodnieniu z Programistą (@KamilGammert) należy stworzyć Diagram klas wykorzystując zaakceptowany przez Klienta zarys Diagramu klas utworzony dnia 17.03.2015r. Zarys diagramu klas został dostarczony do Analityka przez Kierownika grupy projektowej.

**Comment by AndrzejPietrzak** [comment]
Dodano diagram klas stworzony w porozumieniu z programistą.

**Comment by DamianGraczyk** [comment]
Proszę poprawić diagram klas projektu aplikacji mobilnej "Milionerki" używając znaczników Android.view::, Android.hardware::, Android.app:: itp. w nazwach klas, w których są one używane.

**Comment by AndrzejPietrzak** [comment]
Poprawiono.

**Comment by DamianGraczyk** [comment]
Obecna wersja diagramu klas wymaga omówienia jej z Klientem. Wątek zostanie ponownie otworzony w przypadku konieczności dokonania zmian w diagramie klas.
